/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NetInterface {
  name: string
  addr: Array<string>
  macAddr?: string
  index: number
  isUp: boolean
  constructor(name: string, addr: Array<string>, macAddr?: string, index: number, isUp: boolean)
}

export const IFF_ETH: number

export const IFF_LOOPBACK: number

export const IFF_RUNNING: number

export const IFF_TUNN: number

export const IFF_VPN: number

export const IFF_WIRELESS: number

/**
 * ```
 * let network_interface = network_interface();
 *
 * ```
 */
export declare function interfaces(filter: number): Array<NetInterface> | null
